import mercury from "@mercury-js/core";
export const User= mercury.createModel("User",{
  userName:{
    type:"string"
  },
  email:{
    type:"string",
    unique:true
  },
  password:{
    type:"string",
    bcrypt:true
  },
  phone:{
    type:"string"
  },
  role:{
    type:"enum",
    enumType:"string",
    enum:["ADMIN","COACH","PLAYER","SPONSOR","SUPER_ADMIN"],
    default:"PLAYER"
  },
  token:{
    type:"string"
  },
  profilePic:{
    type:"relationship",
    ref:"File"
  },
  isActive:{
    type:"boolean",
    default:true
  },
})